Standardizing on StormForge Performance Testing nomenclature.
thestormforge/examples pull request #52
Opened 2021-05-18 18:33 UTC by ztreinhart

This PR replaces references to "Stormforger" with "StormForge Performance Testing" to standardize on the current branding. Docs and directory names have been changed where applicable, but no changes have been made inside any YAML files, etc. 

Signed-off-by: Zach Reinhart <zach@stormforge.io>

2021-05-19 07:51 UTC, zeisss commented on hpa/sf-perftest/README.md
> +# Voting Webapp with HPA optimized using StormForge Performance Testing load test
```suggestion
# Voting Webapp with HPA optimized using StormForge Performance Testing
```

thats a bit too much.

2021-05-19 07:53 UTC, zeisss requested changes
just some small nitpicks

2021-05-19 07:53 UTC, zeisss commented on webserver/README.md
>  - [Locust](locust.io)
```suggestion
- [Locust](https://locust.io)
```

2021-05-19 07:53 UTC, zeisss commented on hpa/README.md
> +We show how to define such stormforge optimization experiment using two load test engine: [Locust](locust.io) and [StormForge Performance Testing](https://www.stormforge.io/performance-testing/)
```suggestion
We show how to define such stormforge optimization experiment using two load test engine: [Locust](https://locust.io) and [StormForge Performance Testing](https://www.stormforge.io/performance-testing/)
```

2021-05-19 16:56 UTC, tisba approved these changes
Looks good to me 👍

2021-05-20 07:29 UTC, zeisss approved these changes

2021-05-20 14:02 UTC, merged